[IMP] Added promeheus-exporter capabilities & nginx cache cusomisation capabilities
camptocamp/docker-odoo-nginx pull request #26
Opened 2023-06-27 07:23 UTC by wouitmil

2023-06-27 08:19 UTC, vrenaville commented on 9.0/Dockerfile
> +RUN wget https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.10.0/prometheus-nginxlog-exporter_1.10.0_linux_arm64.tar.gz
can we fork this repo into camptocamp org ?

2023-06-27 08:21 UTC, vrenaville commented on 9.0/templates/nginx.conf.tmpl
> +    add_header Strict-Transport-Security "max-age=600; includeSubDomains" always;
5TxEffER5vjrPe4This part was for test, I think it should be revert to original when we will merge to master

2023-06-27 08:22 UTC, vrenaville commented on 9.0/templates/nginx.conf.tmpl
> +      add_header Strict-Transport-Security "max-age=600; includeSubDomains" always;
same here

2023-06-27 08:22 UTC, vrenaville commented on 9.0/templates/nginx.conf.tmpl
>        # there is no inheritance of proxy_set_header, as soon as we define one at a level,
same here

2023-06-27 08:24 UTC, vrenaville commented
@wouitmil did you have test this image on our test instance, do we know if it has latency due to log writing
 ?

2023-06-27 08:26 UTC, vrenaville requested changes
I would like to have this branch devel tested first :) on a customer instance.

we will need to adapt the helm package to add servicemonitore entry point

2023-06-28 15:30 UTC, gurneyalex commented on 9.0/templates/nginx.conf.tmpl
> +  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=one:100m inactive=60m;
```suggestion
  # 20MB of shared memory for cache keys, inactivity delay 1h before forced purge (do we need this?) 
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=one:100m inactive=1h;
```

Documentation for the directive is on: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path

Now, reading the doc: keys_zone at 10MB is probably enough, 100MB is very likely way too much

> all active keys and information about data are stored in a shared memory zone, whose name and size are configured by the keys_zone parameter. One megabyte zone can store about 8 thousand keys. 

so 10M gives 80k cached entries, maybe we want to raise this to 20M but 100M  sounds really high. 

`max_size` is a better parameter if we want to control the on disk space (or `min_free` if we only want to control the free amount of disk we want to keep -> this is likely tied to the use of a docker volume -> to check what space we have (and ensure /var/cache/nginx is on a volume, and not on the overlayfs).

2023-07-03 07:35 UTC, simahawk commented on 9.0/templates/config.hcl.tmpl
> +    website = "ocms"
ocms?

2023-08-08 09:15 UTC, closed without merging